### PR TITLE
Ensure minimist is at least v1.2.3 in dependencies

### PR DESCRIPTION
**Pull request by ryandberger**
because of prototype pollution security issue. See here for more info: https://app.snyk.io/vuln/SNYK-JS-MINIMIST-559764

### CODE REVIEW

**Comment by ryandberger** [comment]
> Er, there's waaaaay more going on here than than just incrementing mimimist, e.g. I don't think we want these changes in `install.json` or `okapi-install.json`. Maybe you intended to merge to `#snapshot` instead?

This is desired for security purposes going forward, but I can certainly put it in snapshot if that is a better place. The `install.json` and `okapi-install.json` changes were automagically made by Jenkins.

**Comment by zburke** [comment]
Opening a PR with this branch against `#snapshot` is certainly a good thing to do and I think will go off without a hitch, but I think we should wait for @funkymalc's approval before we merge this one.

**Comment by funkymalc** [comment]
@zburke @ryandberger - Please open a separate PR to apply this change to snapshot.   I will concurrently ensure this change is also incorporated into the release and master branches.

**Comment by ryandberger** [comment]
> @zburke @ryandberger - Please open a separate PR to apply this change to snapshot. I will concurrently ensure this change is also incorporated into the release and master branches.

Already merged into snapshot. I will close this PR.

**Pull request closed without merging**
