### PR TITLE
Include ui acq repos

### PR DESCRIPTION
**Pull request by NikitaSedyx**
include repos:
* @folio/acquisition-units
* @folio/invoice
* @folio/plugin-find-po-line
* @folio/stripes-acq-components

### CODE REVIEW

**Comment by funkymalc** [comment]
Seems to be some unresolved okapi interface dependency issues here that prevent this PR from merge:

Missing dependency: folio_invoice-1.0.0 requires acquisitions-units: 1.0. Incompatible version for module mod-invoice-1.0.0 interface finance-storage.funds. Need 2.0. Have 1.0/folio_orders-1.5.0/folio_finance-1.5.0/folio_plugin-find-po-line-1.0.0/mod-gobi-1.5.0. Incompatible version for module mod-invoice-1.0.0 interface orders. Need 7.0. Have 6.0/folio_orders-1.5.0/folio_plugin-find-po-line-1.0.0/mod-gobi-1.5.0. Missing dependency: folio_acquisition-units-1.0.0 requires acquisitions-units: 1.0

**Comment by aliaksei-chumakou** [comment]
@funkymalc I think all modules should support finance-storage.funds 2.0. I expect this to be fixed after all modules will be their last release version. 
I'm more concerned about `Missing dependency: folio_acquisition-units-1.0.0 requires acquisitions-units: 1.0`. mod-orders were released already, providing that interface. cc @craigmcnally

**Comment by craigmcnally** [comment]
I'm puzzled by the acquisitions-units interface thing... I can even see that folio-testing has it  
image

this interface is provided by mod-orders and was released in mod-orders-7.0.0... https://github.com/folio-org/mod-orders/blob/840281a9e9017f9de438e9550e8940774ca1559f/descriptors/ModuleDescriptor-template.json#L269

**Comment by craigmcnally** [comment]
I think we should be all set with finance-storage.funds 2.0 as well:  
image

**Comment by craigmcnally** [comment]
OK I've updated the install-extras.json and updated ui-finance to the latest released version.  Dependency issues are resolved and all checks pass, just need an approval now.

**Comment by NikitaSedyx** [comment]
@craigmcnally thanks for your input

@funkymalc seems we are good now

**Pull request merged**
