### PR TITLE
UISACQCOMP-3 remove stripes-acq-components from tenant config

### PR DESCRIPTION
**Pull request by aliaksei-chumakou**
https://issues.folio.org/browse/UISACQCOMP-3

### CODE REVIEW

**Comment by VictorSoroka1** [comment]
Should it also be removed from [package.json](https://github.com/folio-org/platform-complete/blob/snapshot/package.json#L57)?

**Comment by aliaksei-chumakou** [comment]
> Should it also be removed from [package.json](https://github.com/folio-org/platform-complete/blob/snapshot/package.json#L57)?

cc @skomorokh

**Comment by skomorokh** [comment]
Yup! The consuming modules should depend on it directly.

**Comment by VictorSoroka1** [comment]
Yeah, I saw that for the editor you were placing dependent feature in the `dependencies` instead of `devDependencies`.

**Pull request merged**
