### PR TITLE
FOLIO-3568: Add serials-management to snapshot

### PR DESCRIPTION
**Pull request by Jack-Golding**
[FOLIO-3568](https://issues.folio.org/browse/FOLIO-3568)

### CODE REVIEW

**Comment by jakub-id** [comment]
@zburke @wafschneider Guys, let's wait for @dcrossleyau to review if the modue repo meets the criteria, etc before merging it.

**Review by funkymalc — APPROVED** [review]

**Review by zburke — CHANGES_REQUESTED** [review]
Since my initial approval, a [PR in ui-serials-management](https://github.com/folio-org/ui-serials-management/pull/9) added code that accesses an API without including the corresponding okapi interface.

**Review by dcrossleyau — APPROVED** [review]
The addition to package.json and stripes.config.js are okay.

As explained at the doc https://dev.folio.org/guides/install-frontend-module/#require-backend-only-when-ready
it is okay to merge as-is. However do only require those interfaces when the back-end module that provides them has completed their addition to reference environments.

Note that at this moment some other team has broken the hourly platform builds. So wait to merge this PR until that is rectified.

**Comment by dcrossleyau** [comment]
See my review at [FOLIO-3568](https://issues.folio.org/browse/FOLIO-3568).

> As explained at [this doc](https://dev.folio.org/guides/install-frontend-module/#require-backend-only-when-ready), if the front-end module *does declare* the interface "serials-management" via its package.json okapiInterfaces, then the back-end module mod-serials-management will be automatically included in the platform.
>
> Otherwise the mod-serials-management will need to be temporarily added to the platform-complete snapshot "install-extras.json" file.

**Comment by Jack-Golding** [comment]
The changes regarding the okapiInterfaces for ui-serials management and the copyright/licenses changes for both have been merged this morning

**Review by dcrossleyau — APPROVED** [review]
Thanks. I updated this branch and the build is happy with interface dependencies, showing "mod-serials-management-1.0.0-SNAPSHOT.3".

**Pull request merged**
