### PR TITLE
Stripes 648

### PR DESCRIPTION
**Pull request by ryandberger**
- Fulfills part of https://issues.folio.org/browse/STRIPES-648.
- Updated `eslint-config-stripes` to 5.0.0 which also contains updated version of `eslint`.
- Removed duplicate package reference `@folio/plugin-find-po-line`.
- Fixed minor eslint warning by correcting unused variable syntax to match pattern `/^_/u`.

### CODE REVIEW

**Comment by zburke** [comment]
Hang on. In a [recent discussion on Slack](https://folio-project.slack.com/archives/C2BHMHCFJ/p1571656192101000) we learned ui-marccat requires rxjs v6 to correctly set the headers it sends to Okapi. 

That's not totally resolved yet ([more discussion on Slack#hosted-reference-envs](https://folio-project.slack.com/archives/CFQU1MF61/p1571995410008600)) as there now appears to be a different issue getting ui-marccat to run in the staging environments, but let's hold off on this temporarily.

**Comment by ryandberger** [comment]
> Hang on. In a [recent discussion on Slack](https://folio-project.slack.com/archives/C2BHMHCFJ/p1571656192101000) we learned ui-marccat requires rxjs v6 to correctly set the headers it sends to Okapi.
> 
> That's not totally resolved yet ([more discussion on Slack#hosted-reference-envs](https://folio-project.slack.com/archives/CFQU1MF61/p1571995410008600)) as there now appears to be a different issue getting ui-marccat to run in the staging environments, but let's hold off on this temporarily.

Ah, okay. In order to do that, I'm going to need to update the references in `stripes-connect` first since they are not compatible with rxjs v6. I was getting `yarn build` errors such as:

```
ERROR in ./node_modules/rxjs/Observable.js
Module not found: Error: Can't resolve 'rxjs-compat/Observable' in '/Users/employee/dev/platform-complete/node_modules/rxjs'
 @ ./node_modules/rxjs/Observable.js 6:9-42
 @ ./node_modules/redux-observable/lib/es/ActionsObservable.js
 @ ./node_modules/redux-observable/lib/es/createEpicMiddleware.js
 @ ./node_modules/redux-observable/lib/es/index.js
 @ ./node_modules/@folio/stripes-core/src/configureEpics.js
 @ ./node_modules/@folio/stripes-core/src/App.js
 @ ./node_modules/@folio/stripes-core/src/index.js
 @ multi @folio/stripes-components/lib/global.css ./node_modules/@folio/stripes-core/src/index
```

**Comment by dltj** [comment]
If there is further work to be done, can we close this PR so the EC2 instance isn't running for the weekend?  Thanks!

**Comment by ryandberger** [comment]
> If there is further work to be done, can we close this PR so the EC2 instance isn't running for the weekend? Thanks!

I need to release a new version of `stripes-core` first, so I will close this for now.

**Pull request closed without merging**
